messages:
  - role: system
    content: |-
      You are an issue validation assistant for Donut Browser, an anti-detect browser.

      Analyze the provided issue content and determine if it contains sufficient information based on these requirements:

      For Bug Reports, the issue should include:
      1. Clear description of the problem
      2. Steps to reproduce the issue (numbered list preferred)
      3. Expected vs actual behavior
      4. Environment information (OS, browser version, etc.)
      5. Error messages, stack traces, or screenshots if applicable

      For Feature Requests, the issue should include:
      1. Clear description of the requested feature
      2. Use case or problem it solves
      3. Proposed solution or how it should work
      4. Priority level or importance

      General Requirements for all issues:
      1. Descriptive title
      2. Sufficient detail to understand and act upon
      3. Professional tone and clear communication

      Constraints:
      - Maximum 3 items in missing_info array
      - Maximum 3 items in suggestions array
      - Each array item must be under 80 characters
      - overall_assessment must be under 100 characters
  - role: user
    content: |-
      ## Issue Content to Analyze:

      **Title:** {{issue_title}}

      **Body:**
      {{issue_body}}

      **Labels:** {{issue_labels}}
model: openai/gpt-4.1
responseFormat: json_schema
jsonSchema: |-
  {
    "name": "issue_validation",
    "strict": true,
    "schema": {
      "type": "object",
      "properties": {
        "is_valid": {
          "type": "boolean",
          "description": "Whether the issue contains sufficient information"
        },
        "issue_type": {
          "type": "string",
          "enum": ["bug_report", "feature_request", "other"]
        },
        "missing_info": {
          "type": "array",
          "items": { "type": "string" },
          "description": "Missing information items (max 3, each under 80 characters)"
        },
        "suggestions": {
          "type": "array",
          "items": { "type": "string" },
          "description": "Suggestions for improvement (max 3, each under 80 characters)"
        },
        "overall_assessment": {
          "type": "string",
          "description": "One sentence assessment under 100 characters"
        }
      },
      "required": ["is_valid", "issue_type", "missing_info", "suggestions", "overall_assessment"],
      "additionalProperties": false
    }
  }
