name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What do you want?
      placeholder: Describe the feature and why you need it.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      placeholder: How would you use this feature? What problem does it solve?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
    validations:
      required: true
